#!/bin/bash

PHP_BINARY=""

# Check if PHP exists in /usr/bin/php
if command -v /usr/bin/php &> /dev/null; then
    PHP_BINARY="/usr/bin/php"
# Check if PHP exists in /bin/php
elif command -v /bin/php &> /dev/null; then
    PHP_BINARY="/bin/php"
else
    echo "PHP not found. Please install PHP."
    exit 1
fi

if ! [ -d bin/vendor ] || ! [ -f bin/vendor/autoload.php ]; then
  (
    mkdir -p bin
    cd bin || exit
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    php composer.phar install
  )
fi

"$PHP_BINARY" -d="bin" "bin/mindee.php" "$@"
