#
# Publish Documentation to GitHub pages.
#
name: Publish Documentation

on:
  workflow_call:
  workflow_dispatch:

jobs:
  documentation:
    name: Publish Documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up php ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install phpdocumentor
        run: |
          wget https://phpdoc.org/phpDocumentor.phar
      - name: Build documentation
        run: |
          php phpDocumentor.phar -d ./src -t ./docs/_build
      - name: Move code samples
        run: |
          cp -r ./docs/code_samples ./docs/_build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
