name: Static Analysis

on:
  workflow_call:

jobs:
  static-check:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.1"
        tools: composer

    - name: Install dependencies
      uses: ramsey/composer-install@v3

    - name: Run lint
      run: |
        composer lint

    - name: License Check
      run: |
        ./vendor/bin/license-checker check

    - name: Check Unused Dependencies
      # symfony/console is mistakenly flagged as unused since it is only used in the CLI, not the main app
      # Exclude it from checks.
      run: ./vendor/bin/composer-unused --excludePackage=symfony/console
