#
# Make sure dependencies are all properly integrated and used in the package
#
name: Analyze Dependencies

on:
  workflow_call:

jobs:
  analyze-dependencies:
    name: Run dependencies analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.3
    steps:
      - uses: actions/checkout@v4
      - name: Set up php ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - uses: ramsey/composer-install@v3

      - name: Download archive
        run: curl -OL https://github.com/composer-unused/composer-unused/releases/latest/download/composer-unused.phar

      # symfony/console is mistakenly flagged as unused since it is only used in the CLI, not the main app, so we ignore it.
      - name: check unused dependencies
        run: php composer-unused.phar --excludePackage=symfony/console

      - name: License check
        run: |
          vendor/bin/license-checker check
