#
# Make sure dependencies are all properly integrated and used in the package
#
name: Check for unused dependencies

on:
  - pull_request
  - workflow_dispatch

jobs:
  dependencies-check:
    name: Check for unused depdencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.3
    steps:
      - uses: actions/checkout@v4
      - name: Set up php ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - uses: ramsey/composer-install@v3

      - name: Download archive
        run: curl -OL https://github.com/composer-unused/composer-unused/releases/latest/download/composer-unused.phar

      # symfony/console is mistakenly flagged as unused since it is only used in the CLI, not the main app, so we ignore it.
      - name: run check unused
        run: php composer-unused.phar --excludePackage=symfony/console
