name: Static Analysis

on:
  - push

jobs:
  static-check:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["7.4"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ./vendor
        key: ${{ runner.os }}-${{ hashFiles('composer.json') }}
        restore-keys: |
          ${{ runner.os }}

    - name: Install dependencies
      run: |
        composer install

    - name: Run CS Fixer
      run: |
        ./vendor/bin/php-cs-fixer check ./src

    - name: Run Code Sniffer
      run: |
        ./vendor/bin/phpcs -n ./src/
