name: Regression Tests

on:
  push:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  phpunit-ubuntu:
    name: Run Regression Tests
    timeout-minutes: 30
    strategy:
      max-parallel: 2
      matrix:
        os:
          - "ubuntu-latest"
          # - "windows-latest" # No composer actions are compatible with windows at the moment.
        php-version:
          - 7.4
          - 8.3
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up php ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - uses: ramsey/composer-install@v2
      - name: Unit testing with phpunit
        env:
          MINDEE_API_KEY: ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
        run: |
          ./vendor/bin/phpunit -c tests/regressions.xml
