name: Test Code Samples

on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Run Code Samples
    timeout-minutes: 30
    strategy:
      max-parallel: 2
      matrix:
        php-version:
          - "7.4"
          - "8.2"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Php ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - uses: ramsey/composer-install@v2
      - name: Unit testing with phpunit
        env:
          MINDEE_API_KEY: ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
        run: |
          ./vendor/bin/phpunit -c tests/phpunit.xml

      - name: Tests code samples
        uses: actions/checkout@v4
        with:
          timeout_minutes: 25
          max_attempts: 2
          run: |
            ./tests/test_code_samples.sh ${{ secrets.MINDEE_ACCOUNT_SE_TESTS }} ${{ secrets.MINDEE_ENDPOINT_SE_TESTS }} ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
