name: Unit Tests without PDF support

on:
  push:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  phpunit-ubuntu:
    name: Run Unit Tests on Ubuntu without PDF support
    timeout-minutes: 30
    strategy:
      matrix:
        php-version:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up php ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - uses: ramsey/composer-install@v2
      - name: Unit testing with phpunit
        env:
          MINDEE_API_KEY: ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
        run: |
          ./vendor/bin/phpunit -c tests/pdffeatures.xml

  phpunit-macos:
    name: Run Unit Tests on MacOS without PDF support
    timeout-minutes: 30
    strategy:
      matrix:
        php-version:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up php ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        env:
          phpts: zts
        with:
          php-version: ${{ matrix.php-version }}
      - uses: ramsey/composer-install@v2
      - name: Unit testing with phpunit
        env:
          MINDEE_API_KEY: ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
        run: |
          ./vendor/bin/phpunit -c tests/pdffeatures.xml

  phpunit-windows:
    name: Run Unit Tests on Windows without PDF support
    timeout-minutes: 30
    strategy:
      matrix:
        php-version:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up php ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        env:
          phpts: zts
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, fileinfo, json
      - uses: ramsey/composer-install@v2
      - name: Unit testing with phpunit
        env:
          MINDEE_API_KEY: ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
        run: |
          ./vendor/bin/phpunit -c tests/pdffeatures.xml
